# Generated by Django 3.0.3 on 2020-03-27 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_form', models.TextField()),
                ('drug_class', models.TextField()),
                ('drug_indication', models.TextField()),
                ('drug_contraindication', models.TextField()),
                ('drug_careful', models.TextField()),
                ('drug_side_effect', models.TextField()),
                ('drug_dosage', models.TextField()),
                ('drug_attention', models.TextField()),
                ('drug_reference', models.TextField()),
                ('drug_status', models.BooleanField()),
                ('drug_update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
