# Generated by Django 3.0.3 on 2020-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_foo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
